// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateTimeApp.Models;

namespace PlateTimeApp.Migrations
{
    [DbContext(typeof(NewsFeedContext))]
    [Migration("20190222182815_AddedTitle")]
    partial class AddedTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PlateTimeApp.Models.NewsFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("NewsFeeds");

                    b.HasData(
                        new { Id = 1, Description = "News API has been initialized", Title = "Random Title 1" },
                        new { Id = 2, Description = "User Profile page has been initialized", Title = "Random Title 1" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
