// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateTimeApp.Models;

namespace PlateTimeApp.Migrations
{
    [DbContext(typeof(NewsFeedContext))]
    [Migration("20190313211608_AddedRestaurantNameAndCuisineType")]
    partial class AddedRestaurantNameAndCuisineType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PlateTimeApp.Models.NewsFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CuisineType");

                    b.Property<string>("Description");

                    b.Property<DateTime>("NewsDate");

                    b.Property<string>("RestaurantName");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("NewsFeeds");

                    b.HasData(
                        new { Id = 1, CuisineType = "Pizza", Description = "The third-party deal will supplement the pizza chian's in-house delivery.", NewsDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "Papa John's", Title = "Papa John's partners with DoorDash" },
                        new { Id = 2, CuisineType = "Fastfood", Description = "1000 Degrees Pizza, The Coffee Bean & Tea Leaf, Dos Toros, Fogo de Chão, Grimaldi’s Pizzeria, Growler USA, Jamba Juice, Mimi’s, Num Pang Kitchen, Sizzler and TooJay’s Deli also added new pizzas, seafood dishes and more.", NewsDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Menu Tracker: New items from McDonald's, Fuddruckers, Pie Five" },
                        new { Id = 3, CuisineType = "Grill", Description = "The chain will promote Chipotle Rewards by giving Venmo payouts to fans", NewsDate = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "Chipotle", Title = "Chipotle launches new loyalty program" },
                        new { Id = 4, CuisineType = "Salad", Description = "Co-founder Nathaniel Ru outlines DNA of brand’s success", NewsDate = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "Sweetgreen", Title = "How Sweetgreen creates its intimacy of scale" },
                        new { Id = 5, CuisineType = "Fastfood", Description = "Former hotel executive David Mann tapped for legal, senior vice president roles", NewsDate = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "Dunkin Brands", Title = "Dunkin Brands names new chief legal officer" },
                        new { Id = 6, CuisineType = "Grill", Description = "Marketing chief Maurice Cooper expands duties with digital role", NewsDate = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "Wingstop", Title = "Wingstop names new chief growth officer" },
                        new { Id = 7, CuisineType = "Fastfood", Description = "Staci Rawls played a pivotal P.R. role during the brand’s turnaround", NewsDate = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "KFC", Title = "KFC names first chief communications officer" },
                        new { Id = 8, CuisineType = "Pizza", Description = "Schnatter will drop legal claims after reaching a settlement with the company", NewsDate = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), RestaurantName = "Papa John's", Title = "John Schnatter to exit Papa John’s board" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
